/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio;

/**
 *
 * @author user
 */
public class TablaConver extends javax.swing.JFrame {

    
    
    public TablaConver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnKgLb = new javax.swing.JButton();
        btnSolDol = new javax.swing.JButton();
        btnCaF = new javax.swing.JButton();
        btnFeetMt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        chkInversa = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setText("0");
        txtValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        jLabel1.setText("valor");

        btnKgLb.setText("de Kg a Lb");
        btnKgLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKgLbActionPerformed(evt);
            }
        });

        btnSolDol.setText("de sol a dolar");
        btnSolDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolDolActionPerformed(evt);
            }
        });

        btnCaF.setText("de C° a F°");
        btnCaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaFActionPerformed(evt);
            }
        });

        btnFeetMt.setText("de Feet a Mt");
        btnFeetMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeetMtActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado");

        lblResultado.setText("0.00");

        chkInversa.setText("inversa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkInversa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblResultado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFeetMt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCaF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSolDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKgLb, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblResultado))
                        .addGap(34, 34, 34)
                        .addComponent(chkInversa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKgLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSolDol)
                        .addGap(7, 7, 7)
                        .addComponent(btnCaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFeetMt)
                        .addGap(26, 26, 26))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKgLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKgLbActionPerformed
        // Instanciar la clase Conversiones
        Conversiones conversion = new Conversiones();
    
        double valor = Double.parseDouble(txtValor.getText());
        double resultado = chkInversa.isSelected() 
            ? conversion.lbToKg(valor) 
            : conversion.kgToLb(valor);
    
        lblResultado.setText(String.format("%.2f %s", resultado, chkInversa.isSelected() ? "Kg" : "Lb"));
    }//GEN-LAST:event_btnKgLbActionPerformed

    private void btnSolDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolDolActionPerformed
        // Instanciar la clase Conversiones
        Conversiones conversion = new Conversiones();
    
        double valor = Double.parseDouble(txtValor.getText());
        double tasaCambio = 3.5;

        double resultado = chkInversa.isSelected() 
            ? conversion.dolarToSol(valor, tasaCambio) 
            : conversion.solToDolar(valor, tasaCambio);
    
        String moneda = chkInversa.isSelected() ? "Sol" : "USD";
        lblResultado.setText(String.format("%.2f %s", resultado, moneda));
    }//GEN-LAST:event_btnSolDolActionPerformed

    private void btnCaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaFActionPerformed
        // Instanciar la clase Conversiones
        Conversiones conversion = new Conversiones();
    
        double valor = Double.parseDouble(txtValor.getText());

        double resultado = chkInversa.isSelected() 
            ? conversion.fahrenheitToCelsius(valor) 
            : conversion.celsiusToFahrenheit(valor);
    
        String unidad = chkInversa.isSelected() ? "C°" : "F°";
        lblResultado.setText(String.format("%.2f %s", resultado, unidad));
    
    }//GEN-LAST:event_btnCaFActionPerformed

    private void btnFeetMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeetMtActionPerformed
        // Instanciar la clase Conversiones
        Conversiones conversion = new Conversiones();
    
        double valor = Double.parseDouble(txtValor.getText());

        double resultado = chkInversa.isSelected() 
            ? conversion.feetToMeters(valor) 
            : conversion.metersToFeet(valor);
    
        String unidad = chkInversa.isSelected() ? "Metros" : "Feet";
        lblResultado.setText(String.format("%.2f %s", resultado, unidad));
    }//GEN-LAST:event_btnFeetMtActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        
    }//GEN-LAST:event_txtValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaConver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaConver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaConver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaConver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaConver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaF;
    private javax.swing.JButton btnFeetMt;
    private javax.swing.JButton btnKgLb;
    private javax.swing.JButton btnSolDol;
    private javax.swing.JCheckBox chkInversa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
